// The loopback API's bearer token (AC1): generated by the kernel on first
// start and kept in the macOS Keychain, never in a file, a log or an error.
// Every Keychain call goes through src/auth/keychain.ts.
import { randomBytes as nodeRandomBytes } from "node:crypto";
import type { KeychainReader, KeychainWriter } from "../auth/keychain.js";

/** The Keychain item (service name) holding the API token. */
export const API_TOKEN_KEYCHAIN_SERVICE = "loomwright-studio-api";

/** The item's account label: a fixed constant, never the OS user name. */
export const API_TOKEN_KEYCHAIN_ACCOUNT = "loomwright-studio";

/** 32 random bytes, as 64 lowercase hex characters. */
export const API_TOKEN_BYTES = 32;

const API_TOKEN_PATTERN = /^[0-9a-f]{64}$/;

/** The token could not be produced or the stored item is not one. Never carries the token. */
export class ApiTokenError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "ApiTokenError";
  }
}

/** Whether `value` has the shape the kernel generates (64 lowercase hex characters). */
export function isApiTokenShape(value: string): boolean {
  return API_TOKEN_PATTERN.test(value);
}

function checked(value: string): string {
  if (!isApiTokenShape(value)) {
    throw new ApiTokenError(
      `Keychain item "${API_TOKEN_KEYCHAIN_SERVICE}" does not hold a kernel API token (64 hex characters); delete the item and restart the kernel to generate a new one`,
    );
  }
  return value;
}

/**
 * The API token: the Keychain item's value when it exists; otherwise a new
 * one (`API_TOKEN_BYTES` random bytes as hex) is added under
 * `API_TOKEN_KEYCHAIN_ACCOUNT`, then READ BACK, and what the Keychain holds is
 * returned. The read-back is the only proof the item exists: `security -i`
 * may exit 0 when the command inside it failed. When the add failed because
 * another process created the item first, the read-back wins; when the item
 * is still absent, this throws (the add's own `KeychainError` if it threw).
 */
export function ensureApiToken(
  reader: KeychainReader,
  writer: KeychainWriter,
  random: (size: number) => Buffer = nodeRandomBytes,
): string {
  const existing = reader.read(API_TOKEN_KEYCHAIN_SERVICE);
  if (existing !== undefined) return checked(existing);

  const generated = random(API_TOKEN_BYTES).toString("hex");
  let addError: unknown;
  try {
    writer.add(API_TOKEN_KEYCHAIN_SERVICE, API_TOKEN_KEYCHAIN_ACCOUNT, generated);
  } catch (err) {
    addError = err;
  }
  const stored = reader.read(API_TOKEN_KEYCHAIN_SERVICE);
  if (stored !== undefined) return checked(stored);
  if (addError !== undefined) throw addError;
  throw new ApiTokenError(`Keychain item "${API_TOKEN_KEYCHAIN_SERVICE}" is still absent after adding it`);
}
